/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#a4d1b4",
        "surface-variant": "#e1e3e4",
        "surface-container-high": "#e7e8e9",
        "secondary": "#2b4cda",
        "on-surface": "#191c1d",
        "on-primary-container": "#a8e7c5",
        "on-tertiary-fixed-variant": "#264f39",
        "on-secondary-container": "#fffbff",
        "outline": "#707973",
        "secondary-fixed": "#dee1ff",
        "surface-tint": "#2c694e",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "on-tertiary-container": "#b7e4c7",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#c0edd0",
        "on-background": "#191c1d",
        "primary-fixed": "#b1f0ce",
        "on-secondary-fixed": "#001159",
        "on-secondary-fixed-variant": "#0031c4",
        "on-primary-fixed-variant": "#0e5138",
        "on-error": "#ffffff",
        "surface-bright": "#f8f9fa",
        "inverse-surface": "#2e3132",
        "background": "#f8f9fa",
        "tertiary": "#264f39",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d9dadb",
        "primary-container": "#2d6a4f",
        "on-tertiary": "#ffffff",
        "surface": "#f8f9fa",
        "surface-container-highest": "#e1e3e4",
        "primary": "#0f5238",
        "on-primary-fixed": "#002114",
        "secondary-container": "#4967f4",
        "inverse-primary": "#95d4b3",
        "outline-variant": "#bfc9c1",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#bac3ff",
        "inverse-on-surface": "#f0f1f2",
        "primary-fixed-dim": "#95d4b3",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "on-tertiary-fixed": "#002112",
        "on-surface-variant": "#404943",
        "tertiary-container": "#3e6750",
        "success": "#1b873e",
        "success-container": "#d4f5df"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px"
      },
      spacing: {
        "container-padding": "20px",
        xl: "32px",
        xs: "4px",
        "card-gap": "12px",
        lg: "24px",
        md: "16px",
        unit: "4px",
        sm: "8px"
      },
      fontFamily: {
        "body-sm": ["Manrope"],
        "label-bold": ["Manrope"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "body-lg": ["Manrope"],
        "title-md": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "label-caps": ["Manrope"]
      },
      fontSize: {
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-bold": ["11px", { lineHeight: "14px", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "30px", fontWeight: "700" }],
        "headline-lg-mobile": ["20px", { lineHeight: "26px", fontWeight: "700" }],
        "body-lg": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "title-md": ["15px", { lineHeight: "20px", fontWeight: "600" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["9px", { lineHeight: "12px", letterSpacing: "0.06em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
